name = "eugene-antwi"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "boahemaa-logs"
database_id = "1fe52c6d-c5f3-4eb2-bda1-1c26a378b006"